### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by polluks** [kyx0r/nextvi#95]
Start nextvi, press i
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000008025945 in vc_insert (cmd=105) at vi.c:1206
1206            rep = vi_input(pref, post, cmdo ? -1 : lbuf_slen(ln)+1, row - cmdo);
(gdb) bt
#0  0x0000000008025945 in vc_insert (cmd=105) at vi.c:1206
#1  0x00000000080284f0 in vi (init=1) at vi.c:1734
#2  0x000000000802a3ae in main (argc=1, argv=0x7ffffffee198) at vi.c:2046
(gdb) p cmdo
$1 = 0
(gdb) p ln
$2 = 0x0
```
I suspect https://github.com/kyx0r/nextvi/commit/0f54e1a5f82bb92ef7850da637199ed35ce3a111

**Comment by kyx0r** [comment]
Ehh, maybe not. It can be used to create 0 bytes files similar to touch command. Better leave be :)
